POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "userId": "618b5ea4915a9754dd15dfa0",
    "title": "Shot from the Street",
    "author": "Lizzy Hadfield",
    "url": "https://www.lizzyhadfield.com/",
    "likes": 4
}