PUT http://localhost:3003/api/blogs/619337b7170695287f5ba9c3
Content-Type: application/json

{
    "user:": "61933791170695287f5ba9bc",
    "title": "Shot from the Street",
    "author": "Lizzy Hadfield",
    "url": "https://www.lizzyhadfield.com/",
    "likes": 10
}